### ISSUE TITLE
An alert/error message is to be displayed when a user tries to create a duplicate entry of the same org

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/vachan-api#105]
Issue Description : An alert/error message need to be displayed when a translator tries to create a duplicate entry of the sam organization  
Steps:
Login to AgMT as a translator
Click request admin access
Enter the required details such as organization, email and phone number
Observation : An alert saying organization request sent is displayed

Now click request admin permission again and enter the same organization, same email and phone number.
Observation : It is possible tor create the same organization under the same email login and phone number, resulting in duplication
Expected Result:  On trying to create the same organization , an alert /error message  that prevents the user from creating an org should be displayed such as "This organization has already been created'

**Comment by AnnCherianA** [comment]
The user tries to create the same organization as he/she is not aware whether the previous request for admin access has been approved or not and hence, tries to create the same organization . A warning/ alert mentioning that this is a duplicate entry would be ideal.

**Comment by kavitharaju** [comment]
If the same name and email are used the API already returns a error message that says 'Organization already exits'. You were able to create it again because there were spaces in organization names which made them different in the eyes of the program. This issue has been [fixed](#103) by removing all trailing and preceeding spaces in org name
