### ISSUE TITLE
In ISL-react app production site, it fails to show files from DB 

### ISSUE THREAD

**Issue by JesniJ** [Bridgeconn/vachan-api#439]
In ISL-react app production site: https://isl.bridgeconn.com/ , it fails to show files from data base.

![Screenshot from 2022-10-19 10-46-02](https://user-images.githubusercontent.com/102143707/196604599-0887fbf0-9047-41c4-9b4f-361f3b4cdefe.png)
![Screenshot from 2022-10-19 10-20-26](https://user-images.githubusercontent.com/102143707/196604693-24eff29f-48a1-4ca5-89d5-c607b0785027.png)

**Comment by kavitharaju** [comment]
This happened because all the content on production was given the most restricted permission only ("content")
Have added "open-access" and "publishable" to IRV contents.

But no content has been given the "derivable" permission yet, so none will be available for source upload. Not doing this becasue I am not sure if IRVs are changable.
